### ISSUE TITLE
Rails 5.2.0 - Ruby 2.5.1 - composer fails when composing mysql at higher version

### ISSUE THREAD

**Issue by Juksefantomet** [RailsApps/rails-composer#279]
Hello,

Ubuntu server 16.04 - Running Rbenv ruby 2.5.1 - with multiple apps up and running - rails 5.2.0

A recent attempt with current version yields this:

running --> rails new myapp -m https://raw.github.com/RailsApps/rails-composer/master/composer.rb

1. Build a railsapps starter example application
6. rails-devise
no email
1. puma
same as development
3. MySql
1. ERB
1. none
3. Bootstrap 3.3
1. add jquery-rails gem
2. gmail
1. Devise with default modules
1. none
6. bare
1. none
1. no
disable turbolinks yes
set robots.txt yes
github no
add therubyracer yes

Adding install log and my gems local list
[gem_list_fail_composer.txt](https://github.com/RailsApps/rails-composer/files/2124587/gem_list_fail_composer.txt)
[install_log_mysql_fail_composer.txt](https://github.com/RailsApps/rails-composer/files/2124588/install_log_mysql_fail_composer.txt)

I've done the same with SQlite3, no problems.

I already have an app up and running on latest with the latest.

Suggestion:

Composer when detected multiple mysql gems give you an option to select, or give the option to select multiple versions to deploy.

Thanks!

**Comment by kinoute** [comment]
Same here. Did you find any workaround?

**Comment by Juksefantomet** [comment]
Yes, i installed with SQlite3 and manually swapped to MySql later on. it's a simple swap of Gemfile content.

**Comment by Juksefantomet** [comment]
```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
ruby '2.5.1'
gem 'rails', '~> 5.2.0'
gem 'mysql2', '0.5.1'
gem 'puma', '~> 3.11'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jbuilder', '~> 2.5'
gem 'bootsnap', '>= 1.1.0', require: false
group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end
group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
group :test do
  gem 'capybara', '>= 2.15', '< 4.0'
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'
end
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'bootstrap-sass'
gem 'devise'
gem 'high_voltage'
gem 'jquery-rails'
gem 'therubyracer', :platform=>:ruby
group :development do
  gem 'better_errors'
  gem 'rails_layout'
end
```

```
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: db_development
  pool: 5
  host: 127.0.0.1
  port: 3306
  username: username
  password: password
#  **socket: /opt/local/var/run/mysql5/mysqld.sock**
#  secure_auth: false
#  flags:
#  - -COMPRESS
#  - FOUND_ROWS
#  - MULTI_STATEMENTS

```
